### ISSUE TITLE
Cant make forever log options work

### ISSUE THREAD

**Issue by Snorlock** [zapty/forever-service#10]
Hi im trying to add forever log options in my forever options. But it seems to not be working.

This is my install line:

sudo forever-service install serialReader --script serialReader.js -f " -watchDirectory /home/pi/Code/arduino-plant-reader -w -l readerLog.log -a"

Also, is there a reason to use both watchDirectory and -w? Wouldnt -w just work alone?

**Comment by arvind-agarwal** [comment]
Can you post your /etc/init.d/serialReader? And are you using latest version of forever-service?

**Comment by arvind-agarwal** [comment]
Could you try to run the command without -l option since forever-service overrides that option and stores all logs in /var/log/{service}.log file, I am not sure on -w and --watchDirectory together, I think I picked up example from somewhere and I have been able to successfully use it in my project so haven't tried to further investigate that.

**Comment by Snorlock** [comment]
Ok but you are using it together?
I usually just use -w when i launch forever from the directory im in. But how does that work when you use the service? Does it launch from /etc/init.d/ folder?

**Comment by arvind-agarwal** [comment]
forever-service will change to the same directory from which you run forever-service install cmd before invoking forever command, so if -w works from that directory it should work.

**Comment by Snorlock** [comment]
-w works, but how would .foreverignore work?
Since it runs from same folder and all it works normally?
