### ISSUE TITLE
Why is forever not a dependency?

### ISSUE THREAD

**Issue by markdegrootnl** [zapty/forever-service#13]
As the title says: Why is forever not a dependency? It is listed as a prerequisite in the readme and is seems that this package will not work without forever, so I think you might as well add is as dependency.

**Comment by arvind-agarwal** [comment]
I am not aware of clean way of giving global dependencies, I want to avoid local forever install since it is better to have it globally to benefit from command line it provides.

One alternative is to use npm with in preinstall script, but I am not sure if it will work flawlessly in all environments.

http://stackoverflow.com/questions/6480549/install-dependencies-globally-and-locally-using-package-json

Let me know if you are aware of better method, will be happy to include it.

**Comment by markdegrootnl** [comment]
I guess you're right. Having Forever locally would not be preferably and npm line does not have a direct way to have global dependencies.
