### ISSUE TITLE
how to combine with nodemon

### ISSUE THREAD

**Issue by nvcken** [zapty/forever-service#22]
I usually start node app by following command
forever start -c nodemon app.js --exitcrash

how can I make forever-service work with nodemon ?

**Comment by davidrinnan** [comment]
you can fork the code and make relevant changes to 
 templates/linux/meteor.conf

That is where the upstart configuration commands are managed. 

I am working on an update to MUP in order to be able to pass environment specific configuration via the config file. In my case it is in order to be able to change the default values:
forever -c userdown --minUptime 2000 --spinSleepTime 1000 app/main.js

But with some slight modifications it could be used to add/alter other values. But I havnt looked into detail on your requirement. 

My problem is that I am going away on a holiday for almost two weeks during which notting will happen from my end. 

here you can see work in progress and as you can note it is currently only designed to manage minUptime and spinSleepTime 

https://github.com/davidrinnan/meteor-up/compare/iss-269

**Comment by davidrinnan** [comment]
haha lol you may dissregard my message. I thought it was an issue in the meteor UP project :)

**Comment by arvind-agarwal** [comment]
I would try ```forever-service install myservice -f " -c nodemon" -o " —exitcrash"```

**Comment by arvind-agarwal** [comment]
@nvcken  did that work for you?

**Comment by nvcken** [comment]
I have not test complete yet, because after I run script by following your guide, I run "service myservice_name start"
I get error
```javascript
/etc/init.d/myservice_name : line 61 : forever command not found
starting myservice_name
/etc/init.d/myservice_name : line 75 : forever command not found
```

**Comment by nvcken** [comment]
I put export PATH=/usr/local/bin:$PATH
Then service start was working.
Now, I try test when system restart

**Comment by nvcken** [comment]
@arvind-agarwal 
Yes, It works, Thank you

**Comment by arvind-agarwal** [comment]
you can use -e "PATH=/usr/local/bin:\$PATH" as the parameter in forever-service cli to add the PATH variable to your startup script
